version: '3'

services:
  database:
    image: mariadb
    environment:
      - MYSQL_DATABASE=super_id_db
      - MYSQL_USER=super_id_user
      - MYSQL_PASSWORD=super_id_password
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - ./data/db:/var/lib/mysql
    ports:
      - 6336:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - database
    environment:
      - PMA_HOST=database
      - PMA_PORT=3306
      - PMA_USER=super_id_user
      - PMA_PASSWORD=super_id_password
    ports:
      - 6380:80